import { Match, Standing, PlayerStat } from './types';

export const TEAMS = [
  'Batch 10',
  'Batch 11',
  'Batch 12',
  'Batch 13',
];

export const MATCHES: Match[] = [
  {
    id: '1',
    date: '9 July 2026',
    time: '5:00 PM',
    homeTeam: 'Batch 11',
    awayTeam: 'Batch 12',
    homeScore: 1,
    awayScore: 3,
    status: 'FULL_TIME',
    homeGoals: [{ playerName: 'Antu Das', count: 1 }],
    awayGoals: [{ playerName: 'Shijan Pias', count: 2 }, { playerName: 'Sakib Imtiaz', count: 1 }],
    motm: 'Shijan Pias',
  },
  {
    id: '2',
    date: '9 July 2026',
    time: '6:00 PM',
    homeTeam: 'Batch 12',
    awayTeam: 'Batch 10',
    homeScore: 2,
    awayScore: 1,
    status: 'FULL_TIME',
    homeGoals: [{ playerName: 'Fahim Gazi', count: 1 }, { playerName: 'Shahriar Sakib', count: 1 }],
    awayGoals: [{ playerName: 'Iftikhar Tanvir', count: 1 }],
    motm: 'Fahim Gazi',
  },
  {
    id: '3',
    date: '12 July 2026',
    time: '4:00 PM',
    homeTeam: 'Batch 13',
    awayTeam: 'Batch 11',
    homeScore: 2,
    awayScore: 1,
    status: 'FULL_TIME',
    homeGoals: [{ playerName: 'Abu Riad', count: 1 }, { playerName: 'Aninda Raj', count: 1 }],
    awayGoals: [{ playerName: 'Safi Al Sadi', count: 1 }],
    motm: 'Abu Riad',
  },
  {
    id: '4',
    date: '12 July 2026',
    time: '5:00 PM',
    homeTeam: 'Batch 10',
    awayTeam: 'Batch 13',
    homeScore: 1,
    awayScore: 0,
    status: 'FULL_TIME',
    homeGoals: [{ playerName: 'Iftikhar Tanvir', count: 1 }],
    motm: 'Iftikhar Tanvir',
  },
  {
    id: '5',
    date: '12 July 2026',
    time: '6:00 PM',
    homeTeam: 'Batch 13',
    awayTeam: 'Batch 12',
    homeScore: 1,
    awayScore: 2,
    status: 'FULL_TIME',
    homeGoals: [{ playerName: 'Sami', count: 1 }],
    awayGoals: [{ playerName: 'Shijan Pias', count: 1 }, { playerName: 'Shahriar Sakib', count: 1 }],
    motm: 'Sakib Imtiaz',
  },
  {
    id: '6',
    date: '13 July 2026',
    time: '9:00 AM',
    homeTeam: 'Batch 11',
    awayTeam: 'Batch 10',
    homeScore: 0,
    awayScore: 1,
    status: 'FULL_TIME',
    awayGoals: [{ playerName: 'Anamul', count: 1 }],
    motm: 'Anamul',
  },
  {
    id: '7',
    date: '13 July 2026',
    time: 'TBD',
    homeTeam: 'Batch 12',
    awayTeam: 'Batch 10',
    homeScore: 0,
    awayScore: 0,
    homePenaltyScore: 3,
    awayPenaltyScore: 1,
    status: 'FULL_TIME',
    homePenaltyScorers: ['sakib shahriar', 'a.h. soral', 'seyam'],
    awayPenaltyScorers: ['Shihab'],
    motm: 'a.h. soral',
  },
];

export const STANDINGS: Standing[] = [
  { team: 'Batch 12', played: 4, won: 3, drawn: 1, lost: 0, goalsFor: 7, goalsAgainst: 3, goalDifference: 4, points: 10 },
  { team: 'Batch 10', played: 4, won: 2, drawn: 1, lost: 1, goalsFor: 3, goalsAgainst: 2, goalDifference: 1, points: 7 },
  { team: 'Batch 13', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 3, goalsAgainst: 4, goalDifference: -1, points: 3 },
  { team: 'Batch 11', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 2, goalsAgainst: 6, goalDifference: -4, points: 0 },
];

export const PLAYER_STATS: PlayerStat[] = [
  { name: 'Shijan Pias', team: 'Batch 12', goals: 3 },
  { name: 'Shahriar Sakib', team: 'Batch 12', goals: 2 },
  { name: 'Iftikhar Tanvir', team: 'Batch 10', goals: 2 },
  { name: 'Sakib Imtiaz', team: 'Batch 12', goals: 1 },
  { name: 'Antu Das', team: 'Batch 11', goals: 1 },
  { name: 'Fahim Gazi', team: 'Batch 12', goals: 1 },
  { name: 'Abu Riad', team: 'Batch 13', goals: 1 },
  { name: 'Aninda Raj', team: 'Batch 13', goals: 1 },
  { name: 'Safi Al Sadi', team: 'Batch 11', goals: 1 },
  { name: 'Sami', team: 'Batch 13', goals: 1 },
  { name: 'Anamul', team: 'Batch 10', goals: 1 },
];
